### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by eachintha** [jfree/jfreechart#122]
I was trying to create exe but, i got this error. 

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/jfree/data/category/CategoryDataset
	at Home.home.jButton5ActionPerformed(home.java:397)
	at Home.home.access$900(home.java:25)
	at Home.home$11.actionPerformed(home.java:206)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)

for freechart 1.0.19.how can i solve this??

**Comment by thackel** [comment]
Way to few information given.

Creating windows executables out of java classes is a technology which is dead sind 20 years ;-)
I would never expect anybody to want or use this approach anymore...

The error message shows that the jfreejar library is not present during runtime.
Not a problem or bug of jfreechart, its a problem of your local setup.
I would suggest to close the ticket :)

**Comment by tomas-pluskal** [comment]
... and do some reading: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by altavir** [comment]
> Creating windows executables out of java classes is a technology which is dead sind 20 years

Well, not quite. There are just different ways to do so like Excelsior JET, GraalVM/Substrate and Jlink wrapper (it does not generate executable, just runs bundled jvm). Without specific information on a technology, it is impossible to give an answer.

**Comment by jfree** [comment]
It is a classpath issue, please check how you have defined your classpath for the app.  Not a JFreeChart issue, so closing it.
