### ISSUE TITLE
jfreechart. FontConfiguration.    NullPointerException

### ISSUE THREAD

**Issue by flyer1212** [jfree/jfreechart#332]
java.lang.NullPointerException: null
  at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
  at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
  at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
  at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
  at sun.font.SunFontManager$2.run(SunFontManager.java:431)
  at java.security.AccessController.doPrivileged(Native Method)
  at sun.font.SunFontManager.<init>(SunFontManager.java:376)
  at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
  at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.lang.Class.newInstance(Class.java:442)

![image](https://user-images.githubusercontent.com/18101769/205198016-bc5567a6-5f20-4cd8-a7b7-85e053ab6594.png)

![image](https://user-images.githubusercontent.com/18101769/205198036-d60559f2-21f4-46c8-9999-d429b285209a.png)

**Comment by jfree** [comment]
I don't see anything related to JFreeChart in there.  I'll close the ticket, please open a new one if you can describe the steps to produce the exception with JFreeChart.
