### ISSUE TITLE
Support for Java 9

### ISSUE THREAD

**Issue by DJViking** [jfree/jfreechart#47]
Tried to run our application with the latest Java 9 build, but JFreeChart wouldn't work.
Is Java 9 support planed for JFreeChart?

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.jfree.fx.FXFontMetrics (in unnamed module @0x2e05b3d6) cannot access class com.sun.javafx.tk.Toolkit (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.tk to unnamed module @0x2e05b3d6
        at org.jfree.fx.FXFontMetrics.<init>(FXFontMetrics.java:65)
        at org.jfree.fx.FXGraphics2D.getFontMetrics(FXGraphics2D.java:894)
        at java.desktop/java.awt.Graphics.getFontMetrics(Graphics.java:257)
        at org.jfree.text.G2TextMeasurer.getStringWidth(G2TextMeasurer.java:79)
        at org.jfree.text.TextUtilities.nextLineBreak(TextUtilities.java:306)
        at org.jfree.text.TextUtilities.createTextBlock(TextUtilities.java:247)
        at org.jfree.chart.title.TextTitle.arrangeRR(TextTitle.java:628)
        at org.jfree.chart.title.TextTitle.arrange(TextTitle.java:496)
        at org.jfree.chart.JFreeChart.drawTitle(JFreeChart.java:1385)
        at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1275)
        at org.jfree.chart.fx.ChartCanvas.draw(ChartCanvas.java:485)
        at org.jfree.chart.fx.ChartCanvas.lambda$new$1(ChartCanvas.java:176)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.base/javafx.beans.property.DoublePropertyBase.fireValueChangedEvent(DoublePropertyBase.java:107)
        at javafx.base/javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:114)
        at javafx.base/javafx.beans.property.DoublePropertyBase.access$000(DoublePropertyBase.java:53)
        at javafx.base/javafx.beans.property.DoublePropertyBase$Listener.invalidated(DoublePropertyBase.java:261)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.base/javafx.beans.property.ReadOnlyDoublePropertyBase.fireValueChangedEvent(ReadOnlyDoublePropertyBase.java:72)
        at javafx.base/javafx.beans.property.ReadOnlyDoubleWrapper.fireValueChangedEvent(ReadOnlyDoubleWrapper.java:103)
        at javafx.base/javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:114)
        at javafx.base/javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:148)
        at javafx.graphics/javafx.scene.layout.Region.setHeight(Region.java:1047)
        at javafx.graphics/javafx.scene.layout.Region.resize(Region.java:1491)
        at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Region.java:2550)
        at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Region.java:2461)
        at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Region.java:2402)
        at javafx.graphics/javafx.scene.layout.BorderPane.layoutChildren(BorderPane.java:603)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1226)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2507)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$3(Toolkit.java:366)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:365)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:392)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)


Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.jfree.fx.FXFontMetrics (in unnamed module @0x2e05b3d6) cannot access class com.sun.javafx.tk.Toolkit (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.tk to unnamed module @0x2e05b3d6
        at org.jfree.fx.FXFontMetrics.<init>(FXFontMetrics.java:65)
        at org.jfree.fx.FXGraphics2D.getFontMetrics(FXGraphics2D.java:894)
        at org.jfree.text.TextFragment.calculateDimensions(TextFragment.java:230)
        at org.jfree.text.TextLine.calculateDimensions(TextLine.java:194)
        at org.jfree.text.TextBlock.calculateDimensions(TextBlock.java:171)
        at org.jfree.chart.block.LabelBlock.arrange(LabelBlock.java:313)
        at org.jfree.chart.block.BorderArrangement.arrangeNN(BorderArrangement.java:215)
        at org.jfree.chart.block.BorderArrangement.arrange(BorderArrangement.java:141)
        at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
        at org.jfree.chart.block.CenterArrangement.arrangeNN(CenterArrangement.java:286)
        at org.jfree.chart.block.CenterArrangement.arrange(CenterArrangement.java:100)
        at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
        at org.jfree.chart.block.FlowArrangement.arrangeNN(FlowArrangement.java:367)
        at org.jfree.chart.block.FlowArrangement.arrangeRR(FlowArrangement.java:285)
        at org.jfree.chart.block.FlowArrangement.arrange(FlowArrangement.java:160)
        at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
        at org.jfree.chart.title.LegendTitle.arrange(LegendTitle.java:540)
        at org.jfree.chart.JFreeChart.drawTitle(JFreeChart.java:1393)
        at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1286)
        at org.jfree.chart.fx.ChartCanvas.draw(ChartCanvas.java:485)
        at org.jfree.chart.fx.ChartCanvas.lambda$new$1(ChartCanvas.java:176)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.base/javafx.beans.property.DoublePropertyBase.fireValueChangedEvent(DoublePropertyBase.java:107)
        at javafx.base/javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:114)
        at javafx.base/javafx.beans.property.DoublePropertyBase.access$000(DoublePropertyBase.java:53)
        at javafx.base/javafx.beans.property.DoublePropertyBase$Listener.invalidated(DoublePropertyBase.java:261)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.base/javafx.beans.property.ReadOnlyDoublePropertyBase.fireValueChangedEvent(ReadOnlyDoublePropertyBase.java:72)
        at javafx.base/javafx.beans.property.ReadOnlyDoubleWrapper.fireValueChangedEvent(ReadOnlyDoubleWrapper.java:103)
        at javafx.base/javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:114)
        at javafx.base/javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:148)
        at javafx.graphics/javafx.scene.layout.Region.setHeight(Region.java:1047)
        at javafx.graphics/javafx.scene.layout.Region.resize(Region.java:1491)
        at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Region.java:2550)
        at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Region.java:2461)
        at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Region.java:2402)
        at javafx.graphics/javafx.scene.layout.BorderPane.layoutChildren(BorderPane.java:603)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1226)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
        at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2507)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$3(Toolkit.java:366)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:365)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:392)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)


Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.jfree.fx.FXFontMetrics (in unnamed module @0x2e05b3d6) cannot access class com.sun.javafx.tk.Toolkit (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.tk to unnamed module @0x2e05b3d6
        at org.jfree.fx.FXFontMetrics.<init>(FXFontMetrics.java:65)
        at org.jfree.fx.FXGraphics2D.getFontMetrics(FXGraphics2D.java:894)
        at org.jfree.text.TextFragment.calculateDimensions(TextFragment.java:230)
        at org.jfree.text.TextLine.calculateDimensions(TextLine.java:194)
        at org.jfree.text.TextBlock.calculateDimensions(TextBlock.java:171)
        at org.jfree.chart.block.LabelBlock.arrange(LabelBlock.java:313)
        at org.jfree.chart.block.BorderArrangement.arrangeNN(BorderArrangement.java:215)
        at org.jfree.chart.block.BorderArrangement.arrange(BorderArrangement.java:141)
        at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
        at org.jfree.chart.block.CenterArrangement.arrangeNN(CenterArrangement.java:286)
        at org.jfree.chart.block.CenterArrangement.arrange(CenterArrangement.java:100)
        at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
        at org.jfree.chart.block.FlowArrangement.arrangeNN(FlowArrangement.java:367)
        at org.jfree.chart.block.FlowArrangement.arrangeRR(FlowArrangement.java:285)
        at org.jfree.chart.block.FlowArrangement.arrange(FlowArrangement.java:160)
        at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
        at org.jfree.chart.title.LegendTitle.arrange(LegendTitle.java:540)
        at org.jfree.chart.JFreeChart.drawTitle(JFreeChart.java:1393)
        at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1286)
        at org.jfree.chart.fx.ChartCanvas.draw(ChartCanvas.java:485)
        at org.jfree.chart.fx.ChartCanvas.chartChanged(ChartCanvas.java:681)
        at org.jfree.chart.JFreeChart.notifyListeners(JFreeChart.java:1569)
        at org.jfree.chart.JFreeChart.plotChanged(JFreeChart.java:1635)
        at org.jfree.chart.plot.Plot.notifyListeners(Plot.java:1024)
        at org.jfree.chart.plot.Plot.datasetChanged(Plot.java:1288)
        at org.jfree.chart.plot.PolarPlot.datasetChanged(PolarPlot.java:1743)
        at org.jfree.data.general.AbstractDataset.notifyListeners(AbstractDataset.java:232)
        at org.jfree.data.general.AbstractDataset.fireDatasetChanged(AbstractDataset.java:215)
        at org.jfree.data.general.AbstractSeriesDataset.seriesChanged(AbstractSeriesDataset.java:114)
        at org.jfree.data.general.Series.notifyListeners(Series.java:349)
        at org.jfree.data.general.Series.fireSeriesChanged(Series.java:334)
        at org.jfree.data.xy.XYSeries.add(XYSeries.java:551)
        at org.jfree.data.xy.XYSeries.add(XYSeries.java:404)
        at com.company.fx.AntennaPlot.lambda$consolidateDataset$1(AntennaPlot.java:776)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by jfree** [comment]
I haven't really looked closely at Java 9 yet, but for sure the plan is to support it. 

The problem you are running into is in FXGraphics2D.  It uses an internal API to get font metrics from JavaFX rather than AWT/Java2D because it matches more closely with the JavaFX Canvas rendering.  You can switch that off with a rendering hint (KEY_USE_FX_FONT_METRICS) ... set it to false and it will fall back to using AWT/Java2D, but you'll see a few text alignment issues.

Another workaround would be to downgrade to the previous version of FXGraphics2D.

Hopefully Java 9 has added some public API for font metrics on the JavaFX Canvas.  Otherwise, we'll have trouble showing nicely aligned text in JavaFX.

**Comment by tomas-pluskal** [comment]
This is becoming a real issue now that Java 9 is out.

**Comment by jfree** [comment]
I'll try to get an update for FXGraphics2D so it works on Java 9.  Not many changes are required.

**Comment by altavir** [comment]
Could you intermediate maven release after that? It is very hard to use local jars in complicated builds. I was forced to clone repository and use Jitpack to make it work, which is not very good solution.

**Comment by jfree** [comment]
The 1.5.0 release along with JFreeChart-FX 1.0.0 and FXGraphics2D 1.6 should work with JDK9 (and JDK8 of course).

**Comment by altavir** [comment]
It seems to be working.
Happy java 9!

**Comment by jfree** [comment]
Excellent, thanks for confirming!  I'll close the bug report.

**Comment by DJViking** [comment]
Thanks for the update
